name: discord-on-push
on:
  push:
    branches: [main, master]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if secret missing
        run: |
          [ -z "${{ secrets.DISCORD_WEBHOOK_URL }}" ] && echo "Missing DISCORD_WEBHOOK_URL" && exit 1 || true

      - name: Send simple test message to Discord
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python3 - <<'PY'
          import os, json, urllib.request
          url = os.environ["WEBHOOK"]
          payload = {"content": "GitHub Actions → Discord webhook works."}
          req = urllib.request.Request(url, data=json.dumps(payload).encode(),
                                       headers={"Content-Type": "application/json"})
          with urllib.request.urlopen(req) as r:
              print("Discord HTTP status:", r.status)
          PY
