name: discord-on-push
on:
  push:
    branches: [main, master]

# Prefer a secret. If you still have it hard-coded, replace the line below accordingly.
env:
  WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send pretty embed with commit info
        env:
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
          ACTOR: ${{ github.actor }}
          COMPARE: ${{ github.event.compare }}
        run: |
          python3 - <<'PY'
          import os, json, urllib.request, urllib.error, sys

          url = os.environ.get("WEBHOOK")
          if not url:
            print("ERROR: missing WEBHOOK (use secrets.DISCORD_WEBHOOK_URL or hard-code temporarily)", file=sys.stderr)
            sys.exit(2)
          if "?" not in url:
            url += "?wait=true"  # return 200 + body on success

          event_path = os.environ.get("GITHUB_EVENT_PATH")
          if not event_path or not os.path.exists(event_path):
            print(f"ERROR: GITHUB_EVENT_PATH not found: {event_path!r}", file=sys.stderr)
            sys.exit(3)

          with open(event_path, "r", encoding="utf-8") as f:
            evt = json.load(f)

          repo   = os.environ["REPO"]
          branch = os.environ["BRANCH"]
          actor  = os.environ["ACTOR"]
          compare= os.environ.get("COMPARE","")

          head    = evt.get("head_commit") or {}
          head_msg= (head.get("message") or "").splitlines()[0]
          head_url= head.get("url","")
          h
